### ISSUE TITLE
Missing address from application review

### ISSUE THREAD

**Issue by Elfikurr** [prologin/gcc-site#115]
It could be useful to have the address on /application/review/{year}/{event} for every applicant.
When sending mail to accepted applicants.

**Comment by Elfikurr** [comment]
@O-Xian would that be an issue, GDPR wise ?

**Comment by O-Xian** [comment]
> 
> 
> @O-Xian would that be an issue, GDPR wise ?

As long as it is strictly necessary, proportionate, and not accessible to more people than needed.
