### ISSUE TITLE
Dynamically show whether the registration is open

### ISSUE THREAD

**Issue by Elfikurr** [prologin/gcc-site#77]
On the homepage, and the edition page, the 'registration' part should not be hardcoded and should be dynamically updated according to the status of the latest edition's next event.

**Comment by n1tsu** [comment]
What should be the behavior of the 'Registration button' if the subscription is not opened ?
Also I think that the [Issue #14](https://github.com/prologin/gcc-site/issues/14) should be closed since the method `subscription_is_open` solves the request (Added in commit da3ab5e5).

**Comment by Elfikurr** [comment]
The Registration button of the homepage should not be displayed as it, we should not be able to click 'Apply' if no event is open for subscription.
In my opinion, we should add a newsletter page (issue #78 ) to be linked here. Or at the very least add the newsletter subscription part instead of the 'Apply' button !
@fnareoh @remi-dupre what do you think of this ? (this solution & the issue aforementioned)

**Comment by fnareoh** [comment]
I agree, ideally I would put there a message like "No registrations are open at the moment, to receive information, subscribe to the newsletter' and a widget for the newsletter inscription. Thank you!
And I'll close #14 immediately!
