### ISSUE TITLE
Have an easier way of subscribing to the newsletter

### ISSUE THREAD

**Issue by Elfikurr** [prologin/gcc-site#78]
We should have a new page that we could link when we can't people to subscribe to our newsletter.
Also, we should either move or rework the newsletter part of the homepage to make it more visible/accessible.

**Comment by Elfikurr** [comment]
@fnareoh how could we integrate the newsletter widget to the homepage ?
Because #80 will solve this issue only when there is no event open for subscription

**Comment by fnareoh** [comment]
I don't have any issue with adding it below the inscription widget and above the sponsors !

**Comment by Elfikurr** [comment]
So we should remove the logic in #80 that replaces the registration widget with the newsletter widget.

**Comment by fnareoh** [comment]
It might be good to have different text surrounding the widget though

**Comment by Elfikurr** [comment]
For when there is no even open ? Or overall ?
