### ISSUE TITLE
Update/Remove the transport & housing grant

### ISSUE THREAD

**Issue by Elfikurr** [prologin/gcc-site#85]
The email address used should be changed (a @prologin.org address would be better?) and we should update this part according to what we want for this year.
Maybe ask for the applicant a motivation paragraph ?

**Comment by AurelReb** [comment]
Where is this part on the website?

**Comment by Elfikurr** [comment]
It's in the learn_more.html template (gccsite/gccsite/gcc/templates/gcc/learn_more.html).
We still need the answer from @haltode and @fnareoh before going further on this issue !
We could ask @lportemo for an email address and fix this part for now ?
